[versions]
minecraft = "1.12.2"
yarn_build = "533"
fabric_loader = "0.14.24"
loom = "1.4-SNAPSHOT"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "loom" }
legacy_looming = { id = "legacy-looming", version.ref = "loom" }